# Site Settings
title: Esra & Charles Are Getting Married
email: charlesdurban@me.com
description: >
  Charles And Esra Are Getting Married Website
baseurl: ""
url: "http://localhost:4000"
iis_slider_array: []
google_maps_javascript_api_key: "AIzaSyAkyQwpmF5_fUVMuBfpUNmjrap2v3g5R2E"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM