# Permalinks
permalink:           pretty

# Setup
title:               Esra & Charles
tagline:             Are Getting Married
url:                 http://esraandcharlesaregettingmarried.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Charles Durban	
  email:             charlesdurban@me.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/esraandcharlesaregettingmarried/esraandcharlesaregettingmarried.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
